### ISSUE TITLE
ASCII fractal generator done

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#11]
https://raw.githubusercontent.com/ciscoheat/trygve/examples/examples/fractal.k

This was fun, and no big issues really, I left the usual `NOTE` comments. 

I had to use some integers in the `Fractal` Context, so I used private fields. If I expand the example to have different zoom levels, some RoleMethods on the `width_` and `height_` fields would be useful. So the question is again it seems, how to make a built-in type play a Role?

Oh, you may have to copy the output to a text editor with a fixed-width font to see the result as it should be. :)

**Comment by ciscoheat** [comment]
Code has been cleaned up and moved here, I hope you can take a look soon: https://raw.githubusercontent.com/ciscoheat/trygve/bugs/bugs/fractal.k

**Comment by jcoplien** [comment]
I might have a quick look. But I’m working linearly, and right now the && and ! bugs have taken priority.

**Comment by ciscoheat** [comment]
No problem! Fixing the operators would be a great Christmas present. :)

ons 23 dec 2015 13:54 James O. Coplien notifications@github.com skrev:

**Comment by ciscoheat** [comment]
Working fine!
