### ISSUE TITLE
Page 9 of the tutorial (trygve ground zero) the example does not parse!?

### ISSUE THREAD

**Issue by keithy** [jcoplien/trygve#117]
Page 9 of the tutorial (trygve ground zero) the example does not parse!?

```
        int a, b
	a = 1, b = 1
	System.out.println(a == b)
```

K.

**Comment by jcoplien** [comment]
Ah, yes, lots of sloppiness here on my part. First, this is just a code snippet and, second, the snippet has a syntax error. Properly written, it is like this:

{
    int a, b
    a = 1; b = 2
    System.out.println(a == b)
}

Thanks for writing and in general for taking the time. I’ll fix the documentation straightaway, in Version 3.16.

— Cope

**Comment by jcoplien** [comment]
Fixed. Good to go with you, keithy?

**Comment by jcoplien** [comment]
No further activity; presume to be fixed.
