### ISSUE TITLE
User Manual chapter question

### ISSUE THREAD

**Issue by greenozon** [jcoplien/trygve#121]
The first link is broken in the "User Manual" chapter in the readme
https://github.com/jcoplien/trygve#user-manual

if clicked it leads to 404 page

**Comment by jcoplien** [comment]
This works for me. I land on the following page when clicking on that URL:

<img width="1205" alt="PastedGraphic-5" src="https://user-images.githubusercontent.com/7209130/192094905-3b1b88a6-dd17-44a3-9604-71542d3d40da.png">

**Comment by greenozon** [comment]
pardon my misleading description
you did right - but that's just hte 1st step, 2nd - click on the "the oficial one" blue link -> 404

**Comment by jcoplien** [comment]
Sorry for misunderstanding you! In retrospect you were quite clear.

For the time being I have changed the link to point to another free .docx reader. We are likely to soon change the user manual to markup format and will update everything as suitable if and when we do so.

I'll close this for now. Please bark again if I missed the mark.
