### ISSUE TITLE
Date calculations

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#25]
Here's a rundown of the current date problem in #22 `twelve_days_of_christmas.k`:

On line 140, I'm starting with 2015-12-25, adding one day to create the next day. Eventually it will reach 32 and normally this will happen: `new Date(2015,11,32)` -> 2016-01-01

Right now the following dates are generated: 

```
2015-12-25
2015-12-26
2015-12-27
2015-12-28
2015-12-29
2015-12-30
2015-13-1
2015-13-2
2015-13-3
2015-13-4
2015-13-5
2015-13-6
```

Looking closer at `date_test.k` (and the [Date class](https://docs.oracle.com/javase/7/docs/api/java/util/Date.html) in java), I think I know what happens. The test date is `new Date(2015, 12, 25)`, but month is ranged from 0-11, so this date represents 2016-01-25. And to confuse things even more, I see that the year is defined as:

> A year y is represented by the integer y - 1900

This means that 2015 really represents 3915... Quite messy, and the java Date class is also deprecated since java 1.1. What should we do about this?

**Comment by jcoplien** [comment]
I am trying to hide all of the silly internal Java stuff from the user. My months should go 1 - 12, weekdays 1 - 7, years 0 - 2016 ;-), and days of the month 1 - 31. I’ve just scrubbed the code one more time to make sure things look right — but I did just change it in the last one or two pushes, which you may not yet have.

Again: I want the interface to Date to appear as a normal human being (a child) would think of it.

I’ve also updated the documentation.

I made some updates to twelve_days_of_christmas.k and I think it now runs.

If you see anything out of the ordinary with Date, let me know.

**Comment by ciscoheat** [comment]
Sounds great, I'm glad you want to make it more intuitive. Everything works, just made a PR for it.

Speaking of intuitive, what about zero-indices for arrays and lists...?

**Comment by jcoplien** [comment]
> Den 28/12/2015 kl. 15.40 skrev Andreas notifications@github.com:
> 
> Speaking of intuitive, what about zero-indices for arrays and lists...?

Too much water under the bridge for this one. We need to balance between the children, and C programmers ;-)
