### ISSUE TITLE
Expression problem inside switch

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#30]
``` java
class Disk {
    public Disk(int size) {
        size_ = size;
    }

    public int size() const { return size_ }
    public String toString() const { return size_.toString() }

    private int size_;
}

{
        Disk output = new Disk(2);
        System.out.println(output.toString());

        String str = "1";
        switch(str) {
            case "1": 
                // NOTE: Runtime error here
                // Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
                output = new Disk(1);
                System.out.println(output.toString());
                break;
        }
}

/* GOLD:
___________________________________________________________
2
1
*/
```

**Comment by jcoplien** [comment]
Nasty. I’ll have a look.

BTW, thanks for continuing to send these along.

**Comment by jcoplien** [comment]
Andreas,

This is a tough one that gets pretty deep into activation record management. It was moderately hard to find, and the superficial fix was only a couple of lines of code. I think that does it, and all the tests pass, but I want to do more testing with switch and break statements before pronouncing it “done.” It’s quite intricate and I want to make sure that all the scope-cleanup logic is working.

**Comment by jcoplien** [comment]
I’m going to call this one fixed. I did extensive testing and found some problems in other areas, but this fix seems to hold.

**Comment by ciscoheat** [comment]
Sounds good, closing!
