### ISSUE TITLE
More descriptive "too many roles" message?

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#45]
I think it might be helpful if the "too many roles" error had a little more information:
https://github.com/mbrowne/trygve/commit/c7dd8bc9edcabc9ae6125e5365d6906f34a2560e

Cope, I can submit a pull request for this if you agree. And maybe do something about the fact that that message is copied and pasted in RTArrayObject, etc. (I saw your "FIXME" comment in the code).

**Comment by jcoplien** [comment]
I may merge the pull soon. However, I probably want to do within the existing Error APIs instead of creating a new one (there is a discipline I used for dealing with # of arguments). Furthermore, we have to evaluate whether any re-golding needs to be done.

**Comment by mbrowne** [comment]
Ok, I haven't created a pull request yet, I just made this commit in my own fork. Let me know how you want to proceed and I can create a pull request.

**Comment by jcoplien** [comment]
The pull request brings in logic that doesn't quite work right. I've made the fix in 1.3.2, also in RTObjectCommon.java. You can see there how the change was made. Please verify and close this ticket.

**Comment by mbrowne** [comment]
Yes, the more descriptive error is now appearing, thanks.
