### ISSUE TITLE
Strange "Cannot find class, Role, or interface" error

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#46]
I'm getting an error, "Cannot find class, Role, or interface for `Activities'" which doesn't seem to make sense. Minimal example to reproduce:

```
class ActivityList {
    public int size() {
        return 1;
    }
}

context FrontloadActivities
{
    public FrontloadActivities(ActivityList activities) {
        Activities = activities;
    }

    role Activities {   
        public ActivityList getUnplanned() {
            int i = Activities.size();
            return new ActivityList();
        }
    }
    requires {
        int size();
    }
}

___________________________________________________________
line 15: Cannot find class, Role, or interface for `Activities'.
line 15: Type mismatch in initialization of `i'.
```

The error goes away if I either remove the line `int i = Activities.size();` or change the getUnplanned() method to a void return type and remove the return statement.

**Comment by mbrowne** [comment]
This is now fixed. Thanks Cope.

**Comment by jcoplien** [comment]
Thanks, Matt. We can’t raise the quality without folks like you beating on the code. I appreciate every bug report.

I’m working the FrontLoading example right now.
