### ISSUE TITLE
Should simple types be able to play a Role?

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#5]
I started to implement the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) for credit card validation in trygve, and I thought that the last digit in the list of integers should play the role of `CheckDigit`.

I couldn't make this work though, because of the requirement of a RoleObjectInterface for a Role. So is it a mistake to think that `int`, `double` and `boolean` should play a Role in a Context? Here's how I'm thinking:

``` java
context CreditCardValidation {
    role CheckDigit {
        // Compilation error here if no RoleMethods exists.
    } requires {
        // How to specify int, if possible (and reasonable)?
    }

    public CreditCardValidation(CreditCard cc) {
        CheckDigit = cc.number()[15];
    }
}
```

I also get a compilation error if no RoleMethods exist, I'd like to know if that's a bug or feature. :)

**Comment by jcoplien** [comment]
> Den 13/12/2015 kl. 15.44 skrev Andreas notifications@github.com:
> 
> I also get a compilation error if no RoleMethods exist, I'd like to know if that's a bug or feature :)

Hmmm. I can maybe think of degenerate cases where a methodless role might be useful. Let me think about it. I can’t think of any harm in allowing it.

**Comment by runefs** [comment]
I remember Trygve showing a use case for just that. One that spring to mind
is amount in the transfer example. You could argue that amount is a role
but that there's no interaction logic that belongs to the amount

2015-12-13 18:53 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by ciscoheat** [comment]
Yes, that was what I had in mind for the `CheckDigit` role as well. It would be compared to the sum of all digits at the end of the algorithm, so there would be no RoleMethod invokation on it, more like 

```
if (lastDigitInSum == CheckDigit)
```

But your point about a base-10 int wrapper to retrieve the last digit is a good one, @jcoplien. It could require `int::toString` though?

**Comment by jcoplien** [comment]
> Den 14/12/2015 kl. 05.58 skrev Andreas <notifications@github.com <mailto:notifications@github.com>>:
> 
> It could require int::toString though?

It exists.

**Comment by ciscoheat** [comment]
Ah, I tested it on an integer directly, not on an identifier. Thanks.

**Comment by ciscoheat** [comment]
No problem, I will keep reporting. :)
