### ISSUE TITLE
Mutation of stage props is possible

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#53]
I just did a test and found that a stage prop can be mutated indirectly via an instance method that calls some other class (see below). Is this something we should try to prevent / is this possible to prevent?

```
context C {
    public C(A a) {
        R = a;
        R.start();
    }

    stageprop R {
        public void start() {
            test();
            System.out.println("x is now " + getX().toString());
        }
    }
    requires {
        void test() const;
        public int getX() const;
    }
}

class A {
    private int x_ = 0;

    public void test() const {
        new B(this);
    }

    public void setX(int i) {
        x_ = i;
    }

    public int getX() {
        return x_;
    }
}

class B {
    public B(A a) {
        a.setX(1);
    }
}

{
    new C(new A());
}
```

**Comment by jcoplien** [comment]
A stage prop is, in many ways, just a name. In an OO environment any given object can have many names. That a stage prop is being used to address an object doesn’t mean that the object is immune to modification through other paths — some of which may trace back to scripts initiated from the stage prop.

This is in fact a decidable problem but the cost of solving it would be severe, and I don’t think the payoff is worth it. It would essentially mean blocking the invocation of any non-const script on any object currently bound to a stage prop.

By analogy. const-ness in C++ or final-ness in Java are properties of the identifier and not of the object. Neither one makes any guarantees about whether the state of the bound object can be modified. Those languages chose not to solve the problem, and I know of no language that has chosen to solve the problem, other than C++/P back in the 1980s, which did it with protection domains, and some implementations of Ada, which use hardware support to do it.

**Comment by jcoplien** [comment]
Closed with no action per object-composition Email.

**Comment by jcoplien** [comment]
Main issue: To solve it at compile-time would just leave the possibility open for more run-time errors.
