### ISSUE TITLE
Exception to name clash warning for roles played by Context?

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#56]
Follow-up to [issue 52](https://github.com/jcoplien/trygve/issues/52): if the Context itself is playing a role and that role identifier is used to access Context scripts, the programmer will receive a warning like the one below:

```
line 18: WARNING: Script declaration for `amount' has the same name as the Context script declared at line 3
```

The warning is potentially confusing in this case because it will be triggered for _any_ method in the role-object contract, whose sole purpose is to make a Context script accessible (as with `amount()` in the below example).

We may want to have a rewording of the warning message, or an exception whereby it does not get triggered for this special case. On the other hand, we want to discourage programmers from simply making all Context scripts available via a role. Maybe the compiler could check to ensure that any scripts in the role-object contract are in fact used by the role.

```
context TransferMoney {
    private int amount_;
    private int amount() const {
        return amount_;
    }

    public TransferMoney(Account source, Account destination, int amount) {
        SourceAccount = source;
        DestinationAccount = destination;
        amount_ = amount.clone;
        Transfer = this;
    }

    public void run() {
        Transfer.start();
    }

    stageprop Transfer {
        public void start() {
            SourceAccount.withdraw();
            DestinationAccount.deposit();
        }
        public int getAmount() {
            return amount();
        }
    }
    requires {
        private int amount() const;
    }

    role SourceAccount {    
        public void withdraw() {
            if (Transfer.getAmount() > getBalance()) {
                assert(false, "Insufficient funds");
            }
            decreaseBalance(Transfer.getAmount());
        }
    }
    requires {
        void decreaseBalance(int amt);
        int getBalance();
    }

    role DestinationAccount {
        public void deposit() {
            increaseBalance(Transfer.getAmount());
        }
    } requires {
        void increaseBalance(int amt)
    }
}

class Account {
    public Account() {
       balance_ = 0;
    }
    private int balance_;

    public void increaseBalance(int amount) {
        balance_ = balance_ + amount
    }

    public void decreaseBalance(int amount) {
        balance_ = balance_ - amount
    }

    public int getBalance() {
        return balance_;
    }
}
```

**Comment by jcoplien** [comment]
The error message has even removed if it is a "requires" declaration shadowing a Class, Context or Interface declaration.

**Comment by jcoplien** [comment]
This has been fixed. The code compiles without error (except indicating that there is no main expression).

**Comment by mbrowne** [comment]
Thank you.
