### ISSUE TITLE
Template interfaces?

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#60]
I was thinking about this when I made the [WordIterator](https://github.com/jcoplien/trygve/blob/master/tests/spell_check2.k#L74) in the spell checker. Would a template interface be useful enough? So I can create a real iterator interface: 

``` java
interface Iterator<T> {
    boolean hasNext();
    T next();
    void set(T t);
}

class WordIterator implements Iterator<String> {
    ...
```

**Comment by ciscoheat** [comment]
Sorry to make things more complicated, and I agree about the murky territory...! Anyway, here's an attempt:

``` java
interface Iterator<T> {
    boolean hasNext() const;
    T next();
}

class StringIterator implements Iterator<String> {
    public StringIterator(String s) {
        i_ = 0;
        s_ = s.clone;
    }

    public boolean hasNext() const {
        return i_ < s_.length();
    }

    public String next() {
        ++i_;
        return s_.substring(i_-1, i_);
    }

    private int i_;
    private String s_;
}

{
    StringIterator si = new StringIterator("abcdefg");

    while(si.hasNext())
        System.out.println(si.next());
}

/* GOLD:
___________________________________________________________
a
b
c
d
e
f
g
*/
```

I get these errors:

```
line 1:18 no viable alternative at input 'interface Iterator<'
line 30: Missing main expression.
```

**Comment by ciscoheat** [comment]
Closing this too, not so relevant? You decide.

**Comment by jcoplien** [comment]
Naw, keep it open. We may get to it some day. I don’t have a problem with there being a set of backlog requests.

I am very impatient with administrations where the admins are rewarded for keeping a short bug list. The Scrum Alliance is this way and so far they’ve excused themselves out of three of my bug reports so they could close them. They no doubt get a bonus for that. But three bugs remain. One just really bit me (they show my status as not including being a Certified Scrum Trainer®, though I am) and I’m going to raise holly hell about it.

The cursor issue should also have been kept open for the same reason. I’ll see if I can reopen it.

**Comment by jcoplien** [comment]
Finally got around to this, out of boredom. In trygve 3.15. Enjoy, @ciscoheat.
