### ISSUE TITLE
Possible error in instantiation

### ISSUE THREAD

**Issue by runefs** [jcoplien/trygve#61]
I experimented with some initialization and instantiation corner cases. This being my first trygve code. It might be a error code 40 but it seems to be that a derived class with an enforced default constructor doesn't call the super class constructor. Which I would expect it to do

If I remove the last line (md.Blah();) nothing happens at all. If it's there derivedFoo is null

```
class Base {
    public Base() {
        System.out.println("Base constructor");
        Blah(); 
    }
    public void Blah() { }
} 

class Foo{
    private String str_;

    public Foo(String str) {
         str_ = str;
    }
    public void Bar(){ System.out.println("BAR BAR BAR");}
}

class Derived extends Base {
    Foo derivedFoo = new Foo("Derived initializer");
    public void DoIt()
    {
        derivedFoo.Bar();
    } 
}



class MoreDerived extends Derived {
    public void Blah() {
        DoIt(); 
        System.out.println("This should be the last thing printed");
    }
}


{
  MoreDerived md = new MoreDerived();
  md.Blah();
}
```

**Comment by runefs** [comment]
Introducing a default constructor for both Derived and MoreDerive results in the Base constructor being executed as well. However the in-situ initialization of derivedFoo is not executed prior to the invocation of derivedFoo.Bar() resulting in a null ref exception. I would expect the initialization to happen at or before the body of the constructor is invoked

**Comment by jcoplien** [comment]
The version you are running seems out-of-date. The current version generates a warning and a fatal compilation error:

line 13: WARNING: Assignment / initialization does not create a new instance. Both `str_' and`str' will refer to the same object. Use `str.clone' to create a separate instance.
line 19: Improperly formed initialization of`derivedFoo': non-constant right-hand side `[new Foo]'.
line 19: Improperly formed initialization of`derivedFoo': non-constant right-hand side `[new Foo]'.
line 19: Improperly formed initialization of`derivedFoo': non-constant right-hand side `temp$101 = [new Foo]'.

---

The reason that only constant initializations are allowed right now is that it’s in general impossible to know whether an arbitrary identifier in the in situ initialization has itself been initialized. The compiler could be a bit more liberal, but to handle the general case to the permissible limits would require several weeks of work.

**Comment by runefs** [comment]
Yes for some reason I was stuck on a version from december. I have no updated and rewritten the code. the IDE fails with an AWT exception due to line 38 and 53. Both illicit the same error (the one described in Eric Lipperts blog) further I don't think the code should compile without line 48 or something similar. Reading the source of Derived I would feel the programmer made it clear that an object can't be instantiated with 0 as the value for h_. If the above error is fixed the code will still fail due to a breakage of encapsulation. Due to the implicit default constructor h_ has a value that it can't ever have if I instantiate a Derived object. So the private default constructor is essentially made protected.

```
class Base {
    public Base() {
        System.out.println("Base constructor");
        Blah(); 
    }
    public void Blah() {
        System.out.println("base");
    }
} 

class Foo{
    private String str_;

    public Foo(String str) {
         str_ = str.clone;
    }
    public void Bar(String h){ 
        System.out.println("BAR BAR BAR " + h);
    }
}

class Derived extends Base {
    Foo foo;
    int h_;

    private Derived(){
    }

    public Derived(int h){
         if(h == 0) {
            System.out.println("Can't use 0. Choosing a sensible default instead");
            h_ = 1442233;
         } else {
             h_ = h.clone;
         }
    }

    public void DoIt()
    {
        foo = new Foo("Derived initializer");
        foo.Bar("10/" + h_.toString() + " is " + (10/h_).toString());
    } 
}



class MoreDerived extends Derived {
    int i_ = 5;
    public MoreDerived() 
    {
        //super(i_);
        System.out.println("More derived is now constructed");
    }
    public void Blah() {
        DoIt();
        System.out.println("This should be the last thing printed " + i_.toString());
    }
}


{
  MoreDerived md = new MoreDerived();
  md.DoIt();
  md.Blah();
}

/* GOLD:
___________________________________________________________
Base constructor
BAR BAR BAR 10/5 is 2
This should be the last thing printed 5 
More derived is now constructed
BAR BAR BAR 10/5 is 2
This should be the last thing printed 5
*/
```

**Comment by jcoplien** [comment]
> Den 05/02/2016 kl. 14.28 skrev Rune Funch Søltoft notifications@github.com:
> 
> Yes for some reason I was stuck on a version from december. I have no updated and rewritten the code. the IDE fails with an AWT exception due to line 38 and 53. Both illicit the same error (the one described in Eric Lipperts blog) further I don't think the code should compile without line 48 or something similar. Reading the source of Derived I would feel the programmer made it clear that an object can't be instantiated with 0 as the value for h_. If the above error is fixed the code will still fail due to a breakage of encapsulation. Due to the implicit default constructor h_ has a value that it can't ever have if I instantiate a Derived object. So the private default constructor is essentially made protected.

Rune,

There was indeed a bug in the derived class dispatching from a constructor, and in the implicit access of a private method. All fixed. But the general dispatching works as it should. It’s different from your gold. Check it out.

class Base {
   public Base() {
      System.out.println("Base constructor");
      Blah(); 
   }
   public void Blah() {
      System.out.println("base");
   }
}

class Foo {
   private String str_;

   public Foo(String str) {
      str_ = str.clone;
   }
   public void Bar(String h){ 
      System.out.println("BAR BAR BAR " + h);
   }
}

class Derived extends Base {
   Foo foo;
   int h_;

   private Derived(){
   }

   public Derived(int h) {
     if (h == 0) {
        System.out.println("Can't use 0. Choosing a sensible default instead");
        h_ = 1442233;
     } else {
         h_ = h.clone;
     }
   }

   public void DoIt() {
      foo = new Foo("Derived initializer");
      foo.Bar("10/" + h_.toString() + " is " + (10/h_).toString());
   } 
}

class MoreDerived extends Derived {
   int i_ = 5;
   public MoreDerived() {
      Derived(i_);
      System.out.println("More derived is now constructed");
   }
   public void Blah() {
      DoIt();
      System.out.println("This should be the last thing printed " + i_.toString());
   }
}

{
   MoreDerived md = new MoreDerived();
   md.DoIt();
   md.Blah();
}

/\* GOLD:

---

Base constructor
base
More derived is now constructed
BAR BAR BAR 10/5 is 2
BAR BAR BAR 10/5 is 2
This should be the last thing printed 5
*/

**Comment by runefs** [comment]
Yeah that fixed some of it, by calling the local version of Blah and not
the one in the class used for the instantiation (which is why the gold is
different). However the initialization and constructor ordering still has
an issue. I've changed the base declaration to illicit that

class Base {
   int c = 7;
   public Base() {
      System.out.println("Base constructor");
      Blah();
   }
   public void Blah() {
      System.out.println("base " + c.toString());
   }
}

class Foo {
   private String str_;

   public Foo(String str) {
      str_ = str.clone;
   }
   public void Bar(String h){
      System.out.println("BAR BAR BAR " + h);
   }
}

class Derived extends Base {
   Foo foo;
   int h_;

   private Derived(){
   }

   public Derived(int h) {
     if (h == 0) {
        System.out.println("Can't use 0. Choosing a sensible default
instead");
        h_ = 1442233;
     } else {
         h_ = h.clone;
     }
   }

   public void DoIt() {
      foo = new Foo("Derived initializer");
      foo.Bar("10/" + h_.toString() + " is " + (10/h_).toString());
   }
}

class MoreDerived extends Derived {
   int i_ = 5;
   public MoreDerived() {
      Derived(i_);
      System.out.println("More derived is now constructed");
   }
   public void Blah() {
      System.out.println("Blah");
      DoIt();
      System.out.println("This should be the last thing printed " +
i_.toString());
   }
}

{
   MoreDerived md = new MoreDerived();
   md.DoIt();
   md.Blah();
}

/\* GOLD:

---

Base constructor
base 7
More derived is now constructed
BAR BAR BAR 10/5 is 2
Blah
BAR BAR BAR 10/5 is 2
This should be the last thing printed 5
*/

2016-02-05 23:10 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by runefs** [comment]
BTW I like the error message if line 47 is removed

2016-02-06 8:58 GMT+01:00 rune funch søltoft rune@funch.dk:

**Comment by runefs** [comment]
Made it a little more sneaky. Line 6 now calls the Base definition of Blah,
eventhough it's called on an object of type MoreDerived. So the two
invocations of Blah on the same object has different results (updated the
Gold accordingly)

class Base {
   int c = 7;
   public Base(Base self) {
      System.out.println("Base constructor");
      System.out.println("-------");
      self.Blah();
      System.out.println("-------");
   }
   public void Blah() {
      System.out.println("base " + c.toString());
   }
}

class Foo {
   private String str_;

   public Foo(String str) {
      str_ = str.clone;
   }
   public void Bar(String h){
      System.out.println("BAR BAR BAR " + h);
   }
}

class Derived extends Base {
   Foo foo;
   int h_;

   private Derived(){
      System.out.println("never used");
   }

   public Derived(int h, Base b) {
     Base(b);
     if (h == 0) {
        System.out.println("Can't use 0. Choosing a sensible default
instead");
        h_ = 1442233;
     } else {
         h_ = h.clone;
     }
   }

   public void DoIt() {
      foo = new Foo("Derived initializer");
      foo.Bar("10/" + h_.toString() + " is " + (10/h_).toString());
   }
}

class MoreDerived extends Derived {
   int i_ = 5;
   public MoreDerived() {
      Derived(i_, this);
      System.out.println("More derived is now constructed");
   }
   public void Blah() {
      System.out.println("Blah");
      DoIt();
      System.out.println("This should be the last thing printed " +
i_.toString());
   }
}

{
   MoreDerived md = new MoreDerived();
   md.DoIt();
   Base b = md;
   System.out.println("-------");
   b.Blah();
   System.out.println("-------");
}

/\* GOLD:

---

## Base constructor

Blah
BAR BAR BAR 10/5 is 2

## This should be the last thing printed 5

More derived is now constructed

## BAR BAR BAR 10/5 is 2

Blah
BAR BAR BAR 10/5 is 2
This should be the last thing printed 5
*/

2016-02-06 11:05 GMT+01:00 rune funch søltoft rune@funch.dk:

**Comment by jcoplien** [comment]
I think this is all fixed in 1.4.4.

**Comment by runefs** [comment]
I agree

**Comment by jcoplien** [comment]
Thanks, Rune.
