### ISSUE TITLE
Improperly RHS when using a negative int

### ISSUE THREAD

**Issue by runefs** [jcoplien/trygve#67]
The below code can't be parsed. the assignment of -1 is reported as non constant. Am I missing something (another unary operator) or is it a bug?

```
class Collection{
    private Object[] items_;
    private int i_ = -1;
}
```

**Comment by jcoplien** [comment]
Yeah, I’ve been fighting this ambiguity since day 1. So –1 is an expression rather than a constant.

I’ve put a hack into 1.4.8 that will allow this particular case.

> Den 07/02/2016 kl. 17.49 skrev Rune Funch Søltoft notifications@github.com:
> 
> class Collection{
>     private Object[] items_;
>     private int i_ = -1;
> }

**Comment by runefs** [comment]
It's closed. I think a very neat solution would be to mark all operations including only constant expressions as constant. Evaluating them could be left to an optimizer

**Comment by jcoplien** [comment]
I can do that, but there are some interesting edge cases. For example, a const method may be perfectly in scope and it’s perfectly const. However, because of the sequence in which things are initialized within a scope, it may not yet yield an initialized value.

My next step will be to allow computations on constant literals. That’s pretty easy to check with a little recursive function. Maybe that’s what you meant.

Evaluation is not an issue.

**Comment by runefs** [comment]
Yeah I meant constant literals. I think that const methods aren't
constants, as they might yield various results from time to time

2016-02-09 10:20 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by jcoplien** [comment]
> Den 09/02/2016 kl. 11.05 skrev Rune Funch Søltoft notifications@github.com:
> 
> Yeah I meant constant literals. I think that const methods aren't
> constants, as they might yield various results from time to time

But so do constants. See:

https://www.linkedin.com/groups/100895/100895-6100985272944644097

**Comment by runefs** [comment]
Using c++ I think I can argue that any mathematical construct is invalid
but that's not because the construct is indeed invalid :) (I'm not a member
of the group yet, so can't read the actual post)

2016-02-09 11:13 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by jcoplien** [comment]
> Den 09/02/2016 kl. 13.01 skrev Rune Funch Søltoft notifications@github.com:
> 
> Using c++ I think I can argue that any mathematical construct is invalid
> but that's not because the construct is indeed invalid :) (I'm not a member
> of the group yet, so can't read the actual post)

Nirmal George Eapen
Senior Software Developer at Oracle
 https://www.linkedin.com/profile/view?id=ADcAAAbTkckBIL3JH9qitBOae6jnq5ijeWsDP0U&authType=name&authToken=aqtT
Nirmal George Eapen
Senior Software Developer at Oracle
Modification of const value via initializer list

I was just playing around and I figured out that we can modify a const via a initializer list.. Here's the code :-

#include<iostream>

class MyClass{
private:
const int c=5;
int d;
public: 
MyClass();
MyClass(int ,int);
void printValues();
};

MyClass::MyClass() { 
//c=10; -- You cannot assign read only member
std::cout <<"The value of c:"<< c << std::endl;
}

MyClass::MyClass(int a, int b) : c{a}, d{b} { }

void MyClass::printValues(){
std::cout<< "The value of c:" << c << std::endl;
std::cout<< "The value of d:"<< d << std::endl;
}

int main(){
MyClass test;
MyClass Obj{6,10};
Obj.printValues();

return 0;
}

Why is this so and ideally why should that be modifiable via a initializer list , any practical use cases? References to any text books would be really helpful .Thanks in advance for the help and support. 

LikeComment416

Costin Iordache https://www.linkedin.com/profile/view?id=ADcAAAC_mBAByoWxXsiAinMliWwJu3YHCB3b77Y&authType=name&authToken=2swG Saurabh has provided a very accurate answer. Here are my two cents.

Two concepts are mixed together at the same time: 
1. in-class member initializers: https://isocpp.org/wiki/faq/cpp11-language-classes#member-init http://www.linkedin.com/redir/redirect?url=https%3A%2F%2Fisocpp%2Eorg%2Fwiki%2Ffaq%2Fcpp11-language-classes%23member-init&urlhash=BbuE&_t=tracking_anet
2. non-static const class members: they are allowed to and must be initialized in the constructor's initialization list. Any assignment attempt to them in the constructor's body is a modification operation, hence the compile time error in the MyClass default constructor (commented line). In other words, should the in-class initialization of "c" member not be defined, the compiler would ask you to explicitly initialize "c" in all the MyClass constructors but those that delegate construction (https://isocpp.org/wiki/faq/cpp11-language-classes#delegating-ctor http://www.linkedin.com/redir/redirect?url=https%3A%2F%2Fisocpp%2Eorg%2Fwiki%2Ffaq%2Fcpp11-language-classes%23delegating-ctor&urlhash=sQnW&_t=tracking_anet).

Note the subtle difference between the two words, modification and initialization.

**Comment by runefs** [comment]
Yeah as I said c++ can be used to dismiss anything :) an object of a const
type is accoding to the c++ specification not a constant. It can be
modified _after_ initialisation. An initialiser doesn't modify the value of
the variable with const-type it assigns it's initial value, which happens
to make the code in the case above, rather difficult to execute in the head
unless you are really well versed in the standard (which I'm most certainly
not) but in any case I was talking about constant expressions in a
mathematical sense.
This is actually fun. It's the same discussion as with data and state. Most
programmers believe that data is mutable, just as the c++ things that stuff
that's const isn't really constant

2016-02-09 13:58 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by jcoplien** [comment]
> Den 09/02/2016 kl. 19.42 skrev Rune Funch Søltoft notifications@github.com:
> 
> This is actually fun. It's the same discussion as with data and state. Most
> programmers believe that data is mutable, just as the c++ things that stuff
> that's const isn't really constant

:-)

I did post a retort on the list saying that this violates the Rule of Least Surprise and that the Keepers of the Kingdom should be striving to remove such crap from the language.

We can do much better with trygve.
