### ISSUE TITLE
Required context constructor parameters

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#69]
This is related to our [earlier discussion](https://github.com/jcoplien/trygve/commit/8e70df32c622ea9a401e9603df7785740116c4b3#commitcomment-15786451)...

I noticed that implicit constructors are created for contexts too, e.g. this code compiles and runs:

```
context C1 {
    public C1(int x) {
    }
}

{
   new C1();
}
```

Fortunately you can write a private constructor if you want to ensure that the parameter is supplied:

```
context C1 {
    public C1(int x) {
    }
    private C1() {}
}

{
   new C1();  //compile error
}
```

...but I don't think most programmers would know to do that or even wonder if they should until they encountered this behavior by accident.

One solution might be to use a separate 'init' method for initialization, as Cope proposed doing for classes:

```
context C1 {
    public void init(int x) {
    }
}

{
   new C1().init(1);
}
```

**Comment by jcoplien** [comment]
The annoyance of having to provide a default constructor outweighs the rare need to enforce against default initialization. The current implementation works, is in good concert with common practice in existing language, and can be made visible with the user manual if needs be. Until we have a comprehensive design that visibly supports an object mindset absent all the dealings with the class adornments of instantiation and initialization, I think it’s unwise to consider individual suggestions in isolation.

Will not fix.

**Comment by jcoplien** [comment]
Closed as: Will not fix. See above. Please consider a followup that addresses the broader question of the relationship between initialization and instantiation, which is where default initialization tends to be most prominent.

**Comment by mbrowne** [comment]
Well, this wasn't necessarily a request to change the current implementation. My example using an init() method works now, so if that's the approach we want to endorse then no change is needed to the language...but some changes may be needed to the user manual, as you mentioned, and I think our examples should be updated accordingly. (I realize that right now we don't actually have official examples but only a tests folder, so this is more of a future consideration.) Thank you.

**Comment by jcoplien** [comment]
> Den 08/02/2016 kl. 21.20 skrev Matt Browne notifications@github.com:
> 
> Well, this wasn't necessarily a request to change the current implementation

I want the GitHub list to be like a product backlog. Discussion items should go to object-compositon.

**Comment by mbrowne** [comment]
Makes sense and I agree. I opened it here because I thought there might want to consider a change to the implementation, but it seems we've come to an agreement that's not needed. I might raise this again for discussion on the group at some point with regard to examples and documentation.

**Comment by jcoplien** [comment]
> Den 09/02/2016 kl. 00.42 skrev Matt Browne notifications@github.com:
> 
> Makes sense and I agree. I opened it here because I thought there might want to consider a change to the implementation, but it seems we've come to an agreement that's not needed. I might raise this again for discussion on the group at some point with regard to examples and documentation.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/jcoplien/trygve/issues/69#issuecomment-181626256.
> 
> O.K., great.

We may want some kind of “DCI research backlog” that is largely decoupled from trygve. However, if it existed, I’m not totally sure what we’d do with it. Best to leave everyone to follow their research passion.
