### ISSUE TITLE
Missing Assert

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#7]
Any chance of getting a built-in Assert method? Right now I'm using a `new Assert(expression, message)` class.

**Comment by jcoplien** [comment]
> Den 15/12/2015 kl. 01.41 skrev Andreas notifications@github.com:
> 
> Any chance of getting a built-in Assert method? Right now I'm using a new Assert(expression, message) class

There is now a very dumb version, in class Object (once I check in). That limits its usefulness right now but I’m working on it. Also, I’m working on stuff to get it to be able to report line numbers (which is kind of the whole purpose…)

**Comment by ciscoheat** [comment]
Ok, nice! Does this mean it won't be available in Contexts for some time? Thought I noticed that in `new_luhnvalidation.k`.

I tried to trigger an assertion, but nothing happened actually. Nothing happened when I changed it to 
`assert (number == null, "CreditCard null List arg check")`.

**Comment by jcoplien** [comment]
> Den 16/12/2015 kl. 02.08 skrev Andreas notifications@github.com:
> 
> Ok, nice! Does this mean it won't be available in Contexts for some time? Thought I noticed that in new_luhnvalidation.k.

Working on it. Frustrating.

> I tried to trigger an assertion, but nothing happened actually. Nothing happened when I changed it to 
> assert (number == null, "CreditCard null List arg check").
> 
> Hmmm. Works for me. Can you send me a simple, complete example showing the failure?

**Comment by ciscoheat** [comment]
With the latest commit (fb50cfd), when I change line 3 in new_luhnvalidation.k to

`assert (number == null, "CreditCard null List arg check")`

Then the assertion will not fail. Inverting the other assertions works.

A small cosmetic fix: If no assertion message exists, no newline is added after "Assertion failed."

**Comment by jcoplien** [comment]
> Den 16/12/2015 kl. 23.58 skrev Andreas notifications@github.com:
> 
> With the latest commit (fb50cfd https://github.com/jcoplien/trygve/commit/fb50cfd2a122fe3e53c950ad732ec2296511b4ec), when I change line 3 in new_luhnvalidation.k to
> 
> assert (number == null, "CreditCard null List arg check")
> 
> Then the assertion will not fail.
> 
> That’s because the constructor is never called.
> 
> Inverting the other assertions works.
> 
> A small cosmetic fix: If no assertion message exists, no newline is added after "Assertion failed.”
> 
> Fixed.

Lots of little fixes in the works. All the tests pass. But I’  going to spend a lot of time going over the role / stage prop code to make sure it looks right.

**Comment by ciscoheat** [comment]
Can't wait! I'm eager to complete the chord identifier, but #9 is stopping me currently.

**Comment by ciscoheat** [comment]
It does, thank you!
