### ISSUE TITLE
Unused stageprop as type

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#76]
I noticed that the following code compiles and runs, and I'm wondering if it should. (If this is more of a discussion item, we can move it to the group.) Note that the 'Amount' stageprop is never bound, so it's not really a stageprop; it's only being used as a parameter type.

```
context Account {
    public Account(List<LedgerEntry> ledgers) {
        Ledgers = ledgers;
    }

    public Account() {
        Ledgers = new List<LedgerEntry>();
    }

    public void increaseBalance(Amount amount) {
        Ledgers.addEntry("depositing", amount + 0);
    }

    public void decreaseBalance(Amount amount) {
        Ledgers.addEntry("withdrawing", 0 - (amount + 0));
    }

    public int getBalance() {
        return Ledgers.calculateBalance();
    }

    stageprop Amount {} requires {
       int compareTo(int amt) const;
       int +(int amt) const;
       int -(int amt) const;
    }

    role Ledgers {
        public void addEntry(String message, int amount) {
            Ledgers.add(new LedgerEntry(message, amount));
        }

        public int calculateBalance() {
            int sum = 0;
            for (int i = 0; i < Ledgers.size(); i++) {
                sum = sum + Ledgers.get(i).amount();
            }
            return sum;
        }
    }
    requires {
        void add(LedgerEntry entry);
        LedgerEntry get(int pos);
        int size();
    }
}

class LedgerEntry
{
    private String message_;
    private int amount_;

    public LedgerEntry(String message, int amount) {
        message_ = message.clone;
        amount_ = amount.clone;
    }

    public String message() {
        return message_;
    }

    public int amount() {
        return amount_;
    }
}

{
    Account src = new Account();
    src.increaseBalance(30);
    System.out.println(src.getBalance());
}
```

**Comment by ciscoheat** [comment]
I just noticed that it's not possible to use a Role in a `List`, at least not in this situation. Test by replacing the constructor and increaseBalance with this:

``` java
    public Account() {
        Ledgers = new List<LedgerEntry>();
        test_ = new List<Amount>();
    }

    private List<Amount> test_;

    public void increaseBalance(Amount amount) {
        Ledgers.addEntry("depositing", amount + 0);
        test_.add(amount);
    }
```

**Comment by jcoplien** [comment]
What kind of error message were you expecting?

**Comment by mbrowne** [comment]
Maybe a compiler error saying there is no code path that would cause the 
stageprop to be bound. On the other hand, it could be useful to have 
duck types just for the purpose of using them as parameter types and 
return types. But maybe there should be an alternative syntax for that 
to avoid confusion, in the case where it's not actually being used as a 
real stage prop or role. So to sum up: I'm not really sure, but I 
thought I'd report this in case you consider it invalid code.

**Comment by jcoplien** [comment]
> Den 16/02/2016 kl. 21.14 skrev Matt Browne notifications@github.com:
> 
> Maybe a compiler error saying there is no code path that would cause the 
> stageprop to be bound.

Do we know of an algorithm that can identify whether a given line is reachable? That is, are you hoping for us to implement a solution to the halting problem?

> So to sum up: I'm not really sure, but I 
> thought I'd report this in case you consider it invalid code.

So we’re not really sure there is a problem?

**Comment by mbrowne** [comment]
> Do we know of an algorithm that can identify whether a given line is reachable? That is, are you hoping for us to implement a solution to the halting problem?

It's much simpler than that (I think) -- there's no assignment statement binding the `Amount` stageprop to an object in my example. So an error or warning could be thrown whenever the compiler doesn't find an assignment statement for a given role.

> So we’re not really sure there is a problem? 

I'm undecided. So I'll close this for now and may open a new issue later indicating this as a feature request. One idea I had was an alternative syntax for specifying duck types that will never be used as role-object contracts:

```
context Account {
    ...
    type Amount {
        int compareTo(int amt) const;
        int +(int amt) const;
        int -(int amt) const;
    }

    public void increaseBalance(Amount amount) {
        Ledgers.addEntry("depositing", amount + 0);
    }
    ...
}
```

But I'm still thinking about what would be the best approach.

**Comment by jcoplien** [comment]
> Den 17/02/2016 kl. 13.24 skrev Matt Browne notifications@github.com:
> 
> It's much simpler than that (I think) -- there's no assignment statement

Where? In the whole Context?

> binding the Amount stageprop to an object in my example. So an error or warning could be thrown whenever the compiler doesn't find an assignment statement for a given role.

That there be an assignment statement is necessary but not sufficient to guarantee that a Role be bound at run-time. It would only be a heuristic.

If the constructor calls method X and method X contains such bindings, should those count? Or, if we allow re-binding, should that be viewed as a re-binding?

Should multiple assignments to the same Role be allowed? If not, how do we handle conditional bindings (or complete Role bindings within each of two constructors)?

**Comment by jcoplien** [comment]
> Den 17/02/2016 kl. 13.24 skrev Matt Browne notifications@github.com:
> 
> I'm undecided. So I'll close this for now and may open a new issue later indicating this as a feature request.

At this point I think I would want to see it opened as a pull request.

**Comment by mbrowne** [comment]
> Where? In the whole Context?

Yes.

> That there be an assignment statement is necessary but not sufficient to guarantee that a Role be bound at run-time. It would only be a heuristic.

My thinking was that if there's no assignment statement at all, then the role will obviously never be bound. If there is an assignment statement somewhere, then the compiler wouldn't worry about it - maybe it would be bound in a given execution, maybe not. It's more about programmer intent, and understanding how roles and stage props are meant to be used. Is it valid to use a "role" merely as a parameter or return type without ever intending to bind it to an object? I'm leaning toward "no" - I think it muddies things.

**Comment by jcoplien** [comment]
> Den 17/02/2016 kl. 14.42 skrev Matt Browne notifications@github.com:
> 
> Where? In the whole Context?
> Yes.
> 
> This is of no conclusive value — it guarantees nothing about run-time safeness.

Why is the presence of an assignment any more of an indication of the soundness of the programmer’s intent than the declaration of the Role? By default, all Roles are bound to null. And the null value is a valid Role-player.

This is much, more more subtle than any of these discussions have covered so far — which is why I haven’t taken any steps in this direction. There is a whole research career in this for someone.

> That there be an assignment statement is necessary but not sufficient to guarantee that a Role be bound at run-time. It would only be a heuristic.
> My thinking was that if there's no assignment statement at all, then the role will obviously never be bound.
> 
> But it _is_ bound, to null. Are you proposing we stop doing that? That the environment crash on any access of the Role instead of giving an error message when trying to invoke an unsuitable Role-player method on the Role?
> 
> If there is an assignment statement somewhere, then the compiler wouldn't worry about it - maybe it would be bound in a given execution, maybe not.
> 
> And therefore the presence of an assignment conveys zero information.
> 
> It's more about programmer intent, and understanding how roles and stage props are meant to be used.
> 
> The declaration alone should reflect the intent of the programmer to know about and properly treat a Role. Good contexts should be small and to reason about the need to bind it to an object should be a trivial issue.
> 
> Is it valid to use a "role" merely as a parameter or return type without ever intending to bind it to an object? I'm leaning toward "no" - I think it muddies things.
> 
> Well, like I said, you’ re welcome to submit a pull request. But I’d be averse to accepting just a heuristic. If you want to write the trygve equivalent of lint, maybe you can do that. To me, the compiler should be more decisive. And even if these messages are helpful in the odd situation, the good drives out the perfect. I would rather see a cogent example of how to constrain the language so that such enforcement would not be just a heuristic.

**Comment by mbrowne** [comment]
> Why is the presence of an assignment any more of an indication of the soundness of the programmer’s intent than the declaration of the Role? By default, all Roles are bound to null. And the null value is a valid Role-player.

Ah, I wasn't aware of that. I hadn't ever tried to access role in trygve that hadn't been explicitly bound (whether to an object or explicitly bound to null), since I figured that would be an error. But that makes sense and I'm not arguing against it.

BTW I tried the following test code just now:

```
context Account {
    public Account() {
        System.out.println("amount = " + (Amount+0).toString());
    }

    stageprop Amount {} requires {
       int compareTo(int amt) const;
       int +(int amt) const;
       int -(int amt) const;
    }
}

{
    Account src = new Account();
}
```

The output is empty (i.e. it doesn't even output "amount = ") because Amount is null. I'm guessing that applying the `+` operator on any string + null would cause the result of the `+` operation to be null. Would it perhaps be better if null evaluated to an empty string when concatenated with a string, so it would output "amount = " in this case? Java would output "amount = null", which I I have mixed feelings about - that's why I suggested an empty string. If you've already thought through this and it's working as intended then feel free to ignore.

**Comment by runefs** [comment]
> Den 17. feb. 2016 kl. 21.36 skrev James O. Coplien notifications@github.com:
> 
> But it _is_ bound, to null. Are you proposing we stop doing that? That the environment crash on any access of the Role instead of giving an error message when trying to invoke an unsuitable Role-player method on the Role?
> I think this is at least ambiguous. Because the compiler will, in the case of a requires section, tell you that null is not a valid role player.

**Comment by jcoplien** [comment]
> Den 18/02/2016 kl. 07.51 skrev Rune Funch Søltoft notifications@github.com:
> 
> I think this is at least ambiguous. Because the compiler will, in the case of a requires section, tell you that null is not a valid role player.

Yes, this is another complication.

Well, I’m all ears. There are many forces to be balanced here. Some of the proposals here attack a tiny sliver of what is a large, integrated problem. I hope that someone can come up with an integrated proposal or, better, a pull request, that brings these fantasies down to Earth.

**Comment by mbrowne** [comment]
I was not able to reproduce any error when explicitly binding null to a role, with or without a requires section.

**Comment by mbrowne** [comment]
Ah, I think I get it now. Something like this:

```
context C1 {
    public C1() {
        R = null;
    }

    public void test() {
        R.bar();
    }

    role R {
        public void bar() {}
    } requires {
        void foo();
    }
}

{
    new C1().test();
}
```

**Comment by jcoplien** [comment]
> Den 18/02/2016 kl. 19.28 skrev Rune Funch Søltoft notifications@github.com:
> 
> I'll postulate that quite a few of the design discussions we're having are about problems that are the result of design decisions made to make it more Java/C++ like.

I don’t see that.

> That has resulted in the run time environment being more complex than it needs to be and some of the problems probably have no solution within the given structure. 
> To the specific problem of null. When is null a better role player than a strictly typed object representing 'none’?

First, null in trygve is a singular entity, unlike in Java. It is the only value in the language. The internal handling must be much different than it must be in Java.

Second, what would be the difference between the current null and your strictly typed object? What none means is context-sensitive and if the programmer doesn’t like the semantics of none, perhaps we should let the programmer create his or her own (which they can today, though we can make it slightly more convenient with the is and is not operators).

Third, in an idea environment, how would you do it (minding the lack of orthogonality with many other DCI concerns)?

Fourth, if we need to break any latent Java ties, I’m more than happy to do it. Very little of the semantics come from Java — only the syntax. God knows I hate both.

**Comment by runefs** [comment]
2016-02-18 20:17 GMT+01:00 James O. Coplien notifications@github.com:

> > Den 18/02/2016 kl. 19.28 skrev Rune Funch Søltoft <
> > notifications@github.com>:
> > 
> > I'll postulate that quite a few of the design discussions we're having
> > are about problems that are the result of design decisions made to make it
> > more Java/C++ like.
> 
> I don’t see that.

In F# Record types assignment of all fields is required when instantiating
an object of a record type. If you have fields declared with the 'val'
keyword there's a similar requirement. The trick is that the syntax
available in those scope is limited essentially to assignment statements.
For record types reassignment isn't possible (under normal circumstances)
so I'd say the record type and my view on role bindings being immutable and
atomic would help to solve this particular issue

> > That has resulted in the run time environment being more complex than it
> > needs to be and some of the problems probably have no solution within the
> > given structure.
> > To the specific problem of null. When is null a better role player than
> > a strictly typed object representing 'none’?
> 
> First, null in trygve is a singular entity, unlike in Java. It is the only
> value in the language. The internal handling must be much different than it
> must be in Java.
> 
> There's only one null in Java and in both cases it can be used in the place
> of anm object of several different types
> 
> Second, what would be the difference between the current null and your
> strictly typed object? What none means is context-sensitive and if the
> programmer doesn’t like the semantics of none, perhaps we should let the
> programmer create his or her own (which they can today, though we can make
> it slightly more convenient with the is and is not operators).
> 
> I see to possible solutions. Again being inspired by F#. Objects in F#
> can't be null. Instead you'd use a maybe monad. This however would be
> problematic with role bindings (unless we had transient bindings, so that
> in the case of Some the actual object was bound, not the monad) . An
> alternativ approach also commonly used in FP is to declare a specific value
> representing none. I personally prefer to use the latter because it's
> context specific. So in one case it might be "None" where in another it
> might be "Loading" or "Uninitialized"
> 
> Third, in an idea environment, how would you do it (minding the lack of
> orthogonality with many other DCI concerns)?
> 
> We would be back in an applicative approach. My previous idea has been
> evolved to include transient role bindings (as a more generic solution to
> the rolle vector)
> 
> Fourth, if we need to break any latent Java ties, I’m more than happy to
> do it. Very little of the semantics come from Java — only the syntax. God
> knows I hate both.

It not so much the Java ties but the view on the world that Java/C#/C++
shares

**Comment by jcoplien** [comment]
> Den 19/02/2016 kl. 11.58 skrev Rune Funch Søltoft notifications@github.com:
> 
> In F# Record types assignment of all fields is required when instantiating
> an object of a record type.

But this cannot be done syntactically; it requires semantic analysis. I could easily put this in trygve if it’s what we decide to do. But I want to think three times before using semantic analysis to effectively restrict syntax. There are a whole bunch of other semantic considerations:
This approach makes it impossible for two Contexts to refer to each other via Role bindings (and it we replace classes with Contexts, it will make the design reduce to a hierarchy instead of a network).
How about allowing double initialization (initializing the same Role twice)?
If “no,” and if we allow re-binding, then what scimitar do we use to distinguish the cases?
How about base classes (Trygve is considering Context inheritance) and protected fields? Can a derived class initialize a base class Role? Making sure everything is initialized becomes a (most-)derived class concern, then.
Is chained assignment allowed (Role1 = Role2 = object)?
Should in-situ initialization be allowed, and be brought into this policy? If not, it’s an irregularity for both the programmer and compiler.
Is null allowed to be a valid Role-player?
Do we disallow Context constructors from calling each other or do we allow partial initialization in each constructor, as long as all the constructors together bind all Roles?
Can a Role method be invoked from within a constructor? If not, you can’t do piecemeal initialization like I need in my current spell-checking example (under the new “examples” tab in the current trygve release). This restriction would force an unbelievably awkward design.
Do we allow any logic in a Context constructor other than a Role-binding statement? If so,do we allow conditionals? If so, we’ll need dataflow analysis to ensure that all Role bindings are reachable, and we’re back in NP-hard territory. If not, this is a terribly punitive restriction.
There are actually a bunch of others I thought of while out walking, and there are certainly more than I mention here. Many of them must be answered together. It’s a non-localizable language decision and will have to be made carefully.

That’s why I think anyone with the vision of how to do this should create a pull request.

We could dodge a few of these by going all the way to not allowing rebinding, but there is strong sentiment to continue to allow it. Some day we’ll have our functional language but I don’t think it will be trygve.

> If you have fields declared with the 'val'
> keyword there's a similar requirement. The trick is that the syntax
> available in those scope is limited essentially to assignment statements.

It can’t be syntax alone; there must be semantic analysis at work, too. That is, I doubt you see the restriction in the language grammar.

> For record types reassignment isn't possible (under normal circumstances)
> so I'd say the record type and my view on role bindings being immutable and
> atomic would help to solve this particular issue

Pure immutability would be nice, but it’s a next step.
