### ISSUE TITLE
using split in requires seems to fail

### ISSUE THREAD

**Issue by runefs** [jcoplien/trygve#82]
The below code fails with a "No viable alternative", due to split in the requires section. This seems to be a very specific error, so I might have missed something but Iøve tried to rule that out.

```
context program {
     role lines {
     } requires {
          String[] split(String str);          
     }

     public program(String input){
            String[] parts = input.split(" ");
            lines = input;
     }
}
```

**Comment by jcoplien** [comment]
Closing as fixed.
