### ISSUE TITLE
"no viable..." using for loop

### ISSUE THREAD

**Issue by runefs** [jcoplien/trygve#85]
The below code fails to parse with a "no viable..." message

```
class string {

    private List<String> all(){
        List<String> ret;
        for(String char : ret ) {
        }
        return ret;
    }


}
```

**Comment by jcoplien** [comment]
char is a reserved word. It is somewhat vestigial at this point but I’m keeping it in in case I want to re-introduce it later.

> Den 23/02/2016 kl. 20.52 skrev Rune Funch Søltoft notifications@github.com:
> 
> class string {
> 
> ```
> private List<String> all(){
>     List<String> ret;
>     for(String char : ret ) {
>     }
>     return ret;
> }
> ```
> 
> }

**Comment by runefs** [comment]
I'll close it. I think it would be nice with a more informative error message at some point but don't think it should be high on the list at present

**Comment by jcoplien** [comment]
> Den 24/02/2016 kl. 09.07 skrev Rune Funch Søltoft notifications@github.com:
> 
> I'll close it. I think it would be nice with a more informative error message at some point but don't think it should be high on the list at present

Some day I want to make a pass over the whole compiler so it propagates more source information down to the invocations of the low-level hardware primitives, so I can give better diagnostics. I might add a stack backtrace, but even that is largely sanitized from a source perspective.
