### ISSUE TITLE
neither the true body nor the false body is evaluated

### ISSUE THREAD

**Issue by runefs** [jcoplien/trygve#86]
Executing the below code will print

<null>are equal

to the screen. The are two issues. They are on the same line even though they are printed with two calls to println. The more important issue is however that there's no valid way m can be null at the point where it's printed

```

{ 
   String m;
   if("" == " ") {
       m = "are equal";
   } else {
       m "differs";
   }

  System.out.println(m);
  if("" == "") {
       m = "are equal";
   } else {
       m "differs";
   }

   System.out.println(m);
}
```

**Comment by runefs** [comment]
any expression that evaluates to false results in m being unassigned

```
if(false) {
       m = "then";
   } else {
       m "else";
   }
```

will leave m as null is used instead of the first if statement in the example

**Comment by jcoplien** [comment]
Not reproducible here (version 1.5.13).

For this code:

I get:

Enactment starts at line 2, where m is bound to null. The conditional on the if statement at line 3 evaluates to false. The if statement evaluates to ”differs” but the result is discarded. The identifier m remains bound to null. This is printed at line 9. Currently, printing of null results in no newline; I can change that if you like (or you can).

Then the conditional at line 10 evaluates to true. The identifier m is bound to the String literal "are equal". It’s printed at line 16, with proper output.

> Den 24/02/2016 kl. 13.34 skrev Rune Funch Søltoft notifications@github.com:
> 
> { 
>    String m;
>    if("" == " ") {
>        m = "are equal";
>    } else {
>        m "differs";
>    }
> 
>   System.out.println(m);
>   if("" == "") {
>        m = "are equal";
>    } else {
>        m "differs";
>    }
> 
>    System.out.println(m);
> }

**Comment by jcoplien** [comment]
This evaluates exactly as it should. See my other mail.

**Comment by runefs** [comment]
Funny. This was an attempt to create a simple example that reproduced an error I had in some more complex code (I'm currently writing a very simple parser) it behaved similar so I didn't notice the missing "=". That said I think this should be a compile error. There's no meaningful way to use to value expressions. In other words I can't envision when you would write code like that on purpose

Mvh
Rune

**Comment by jcoplien** [comment]
> Den 24/02/2016 kl. 17.55 skrev Rune Funch Søltoft notifications@github.com:
> 
> In other words I can't envision when you would write code like that on purpose

Well, that’s probably true for most of the code I see as a consultant… But it’s perfectly valid code.

The code:

```
if(false) {
    m = "then";
} else {
    m "else";
}
```

is roughly equivalent to:

```
if(false) {
    m = "then";
} else {
    m;
            "else";
}
```

That is, a trygve program is just a sequence of declarations and expressions, and both m and "else” are valid expressions.

What you write isn’t good idiomatic trygve. You might better write:

```
m = if(false) {
         "then"
    } else {
        "else"
    }
```

or just:

```
m = if(false) "then" else  "else"
```

If you have concrete suggestions for what kind of error / warning to issue, and when, I need some guidance. But right now I’m of the opinion that the compiler can’t always protect a programmer against himself or herself. And there are places to use value expressions, as I showed above. I suspect that more idiomatic cases will arise — as they did in C, largely due to Brian Kernighan.

I can redesign the language to be very unforgiving and to require semicolons at every turn: that would mitigate the kind of problem you had. It also blocks most of the incremental steps toward side-effect-free programming. Remember that trygve is a research vehicle, and I’m focusing more on making it handle correct code correctly than to optimize for the most efficient treatment of syntax errors or dubious semantic constructs.

**Comment by runefs** [comment]
I had missed that it was an if expression. Which I personally prefer to an
if statement. The java syntax constrained my thinking I guess :). I find
that some guidance with informative error messages makes experimentation
more efficient since more time is spent on experimenting and less on "why
doesn't this work" if that would bump it to the top I'm less sure about

2016-02-24 18:16 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by runefs** [comment]
I had missed that it was an if expression. Which I personally prefer to an
if statement. The java syntax constrained my thinking I guess :). I find
that some guidance with informative error messages makes experimentation
more efficient since more time is spent on experimenting and less on "why
doesn't this work". In F# it's a warning if you silently discard the value
of an expression. That has saved me from quite a few errors, so if I was to
suggest any improvement that would be it

2016-02-24 18:16 GMT+01:00 James O. Coplien notifications@github.com:

**Comment by jcoplien** [comment]
> Den 24/02/2016 kl. 19.30 skrev Rune Funch Søltoft notifications@github.com:
> 
> I find
> that some guidance with informative error messages 

It’s not an error.

I’d give an informative message if we could identify the situations where the messages wouldn’t end up drowning the programmer in stuff they already knew about, at the potential expense of obscuring (just by the shear mass of their presence) the important messages.

Can you delineate the context under which I should issue a message?

This doesn’t seem like a frequent enough problem to incur the risk of additional error babbling.

**Comment by jcoplien** [comment]
Thanks, Rune. Keep it in mind and if you can think of any kind of helpful analysis I could provide to users who run afoul of this, let me know.
