### ISSUE TITLE
Private instance methods are accessible

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#87]
Follow-up to our [conversation](https://groups.google.com/d/msg/object-composition/W09d-N1F2Cg/wkRTLZzvGAAJ) on the group... here's an example that compiles and runs:

```
class A {
    private void foo() {}
}

context C {
    public C(A a) {
        R = a;
    }

    public void test() {
        R.callFoo();
    }

    role R {
        public void callFoo() {
            foo();
        }
    } requires {
        void foo();
    }
}

{
    new C(new A()).test();
}
```

I thought maybe that was because the requires contract didn't specify an access modifier. But it still compiles and runs even if you change the `requires` section to:

```
requires {
    private void foo();
}
```

Personally I still wonder if there might be some cases where this _should_ be allowed, but if so then there should probably be some syntax restricting it to particular roles or Contexts rather than allowing _any_ role to access the private instance methods of its players.

**Comment by jcoplien** [comment]
tests/matt4.k is another one (from you ;-) )

**Comment by jcoplien** [comment]
and tests/matt_money_xfer.k

**Comment by mbrowne** [comment]
I was originally thinking in terms of my experience programming in PHP, where methods are public by default in the absence of any access modifier. I should have known better since that's not how it works in Java. So I think it's fine that those older tests will break; I can add `public` modifiers to my earlier examples where appropriate if that's helpful.

**Comment by jcoplien** [comment]
Fixed in 1.5.14.

**Comment by mbrowne** [comment]
Thanks.

**Comment by jcoplien** [comment]
Thanks, Matt.
