### ISSUE TITLE
Map<K,V> containsKey not working with String keys

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#88]
Script `boolean containsKey(K key)` seems not to work as intended when using String keys.

``` java
{
    List<String> l = new List<String>()
    l.add("a")
    System.out.println(l.contains("a"))

    Map<int, String> m1 = new Map<int, String>()
    m1.put(1,"opt a")
    System.out.println(m1.containsKey(1))

    Map<String, int> m2 = new Map<String, int>()
    m2.put("a", 1)
    System.out.println(m2.containsKey("a"))

    Map<String, String> m3 = new Map<String, String>()
    m3.put("a","opt a")
    System.out.println(m3.containsKey("a"))
}
/*
___________________________________________________________
true
true
*/
```

**Comment by jcoplien** [comment]
I cannot reproduce a problem.

When I compile and run this under 1.5.17, I get;

---

true
true

> Den 01/03/2016 kl. 20.27 skrev Héctor Adrián Valdecantos <notifications@github.com <mailto:notifications@github.com>>:
> 
> {
>     List<String> l = new List<String>()
>     l.add("a")
>     System.out.println(l.contains("a"))
> 
> ```
> Map<int, String> m1 = new Map<int, String>()
> m1.put(1,"opt a")
> System.out.println(m1.containsKey(1))
> 
> Map<String, int> m2 = new Map<String, int>()
> m2.put("a", 1)
> System.out.println(m2.containsKey("a"))
> 
> Map<String, String> m3 = new Map<String, String>()
> m3.put("a","opt a")
> System.out.println(m3.containsKey("a"))
> ```
> 
> }

**Comment by hvaldecantos** [comment]
I am using 1.5.16, right now it is the last version git pulls from master branch. Shouldn't we get:

```
/*
___________________________________________________________
true
true
true
true
*/
```

**Comment by jcoplien** [comment]
Found it. Dumb programming error. It will be in the next push — but there’s more I’d like to clean up before the next commit. If you’d like this pushed urgently let me know and I can do it. Thanks for the report! — Cope

**Comment by hvaldecantos** [comment]
You're welcome! Similar problem in `Map<K,V>.remove(K key)` when using `String` keys , script fails silently. I though it was  `containsKey` problem propagation, but it seems not. Run under version 1.5.17

``` java
{
    Map<int, String> m1 = new Map<int, String>()
    m1.put(1,"opt a")
    System.out.println(m1.containsKey(1))
    System.out.println(m1.remove(1))
    System.out.println(m1.containsKey(1))

    Map<String, String> m2 = new Map<String, String>()
    m2.put("a","opt a")
    System.out.println(m2.containsKey("a"))
    System.out.println(m2.remove("a"))
    System.out.println(m2.containsKey("a"))
}/*
___________________________________________________________
true
opt a
false
true
*
```

We should get:

``` java
/* GOLD:
___________________________________________________________
true
opt a
false
true
opt a
false
*/
```

**Comment by jcoplien** [comment]
Yup, same problem. And I found one more — in Map.contains().

I’ll push a fix soon. I want to have a quick look at your compareTo() problem to see if I also can quickly figure it out.

**Comment by hvaldecantos** [comment]
Thanks, it seems fixed.

**Comment by jcoplien** [comment]
Thanks, Héctor.
